bin/www
routes/index.js
views/login.pug
views/register.pug

[수정] 로그인페이지 완료 (#1)

---

package-lock.json
package.json
routes/users.js
views/register.pug

- 회원가입 선택 입력 페이지 구성 완료
- 회원가입 api 작성 완료
- register api front와 연동 완료

회원가입 페이지 작업

---

views/register.pug

[수정] 회원가입 페이지 필수정보 입력칸 추가

---

public/javascripts/register.js
public/javascripts/validations.js
views/register.pug

회원가입 페이지 필수정보에 validation 적용 #32

---

lib/UserManager.js
routes/index.js
views/complete_register.pug

가입완료 페이지 작성

---

lib/UserManager.js

user를 db에 저장하고 불러오는 클래스입니다.
close #29

UserManaer 만들기

---

public/javascripts/register.js
routes/users.js
views/layout.pug
views/register.pug

전체 동의 누르면 필수 항목, 광고 수신 클릭 되게 기능 구현
전체 동의 눌려진 상태에서 필수항목 or 광고 수신 클릭 해제하면 전체동의 체크 해제
close #14

[수정] 약관 동의 체크박스 구현 완료

---

routes/users.js

/api/phone_auth?auth_number={number}
길이 6이면 인증 성공.
close #40

[수정] 백엔드 핸드폰 인증 api 추가

---

public/javascripts/register.js
public/stylesheets/style.css
views/register.pug

[추가] 주소찾기 버튼 활성화 및 기능

---

public/stylesheets/style.css
views/layout.pug
views/register.pug

stylesheet 중간 PR#44

---

public/stylesheets/style.css
views/register.pug

layout, button, submit button 클래스 만들고 회원가입 페이지에 적용했습니다. #44

버튼 스타일/회원가입 페이지 중간 PR

---

public/stylesheets/style.css
views/register.pug

스타일 시트 만들기/회원가입 페이지 스타일 적용

---

public/stylesheets/style.css
views/complete_register.pug
views/includes/logo.pug
views/login.pug
views/register.pug

로고 만들고 페이지에 추가

---

lib/sessionMiddleware.js
public/stylesheets/style.css
routes/index.js
views/index.pug

- 로그인 시 메인 페이지에서 유저 이름을 표시합니다.
- 메인 페이지가 예뻐졌습니다.
close #4 #5

메인 페이지 렌더/스타일 작업

---

public/javascripts/register.js
public/javascripts/validations.js

이메일 validation이 잘 작동합니다.
- email validation 정규식 수정
- email validation시 스타일 클래스 추가/삭제 로직 구현
close #41 
close #60

[수정] 이메일 렌더링/validation 수정

---

routes/index.js
views/index.pug

- 로그인 시 메인 페이지에 로그인 버튼 대신 로그아웃 버튼이 생깁니다.
- 버튼을 누르면 `/logout`으로 연결됩니다.
- `/logout`에서는 세션을 지우고 `/`로 리다이렉트합니다.
close #59

로그아웃 기능 추가

---

public/stylesheets/style.css
views/complete_register.pug

가입완료 페이지 스타일 작업 했습니다.
클래스 명 정리가 필요해보입니다.
closes #22

[수정] 가입완료페이지 스타일 작업 #22

---

public/stylesheets/style.css
views/login.pug

[수정] 로그인 페이지 스타일 작업 #3

---

app.js
routes/users.js

[수정] lib -> service 폴더 오류 수정

---

public/javascripts/register.js
public/javascripts/validations.js
routes/users.js

만들고 보니까 assign되어있었네요.
일단 지금은 아이디 길이가 7 이상이면 통과되게 만들었어요.

[추가] 아이디 체크 시 중복검사 #48

---

public/javascripts/register.js
public/javascripts/validations.js
views/register.pug

인증 부분 함수를 고쳐봤는데 아직도 좀 복잡한것 같아요. 어떻게 하면 더 간단해질까요
close #68

핸드폰 인증 부분 리팩터

---

public/javascripts/register.js
public/stylesheets/register.css
public/stylesheets/style.css
views/complete_register.pug
views/index.pug
views/layout.pug
views/register.pug

회원가입 모달 스타일 작업

---

public/javascripts/register.js

연관있는 함수들을 묶어놓았다. 이제 에디터에서 브레켓을 닫을 수 있다.

[수정] register.js 리팩터링

---

db/users.db
models/userModel.js
routes/users.js
service/userService.js

[기능] 회원가입 기능 완료

---

routes/users.js
service/userService.js

[추가] 회원가입 id 중복검사완료  (#15)

---

models/userDTO.js
public/javascripts/login.js
routes/users.js
service/sessionMiddleware.js
service/userService.js
views/index.pug
views/layout.pug
views/login.pug

[추가] 로그인 기능 구현 #23

---

db/users.db
routes/users.js
service/userService.js
service/validations.js

[수정] 회원가입 화면 수정

---

service/userService.js

UserDTO삭제하고
id, password 일치하는 항목 찾아서
리턴하도록 수정했습니다.

[수정] 로그인 함수 수정

---

db/users.db
public/javascripts/register.js
service/userService.js
views/register.pug

대충 작업 했습니다.
- 체크 다시 할 때 에러메시지 없애기.
close #85

[수정] 회원가입 필수 동의 정보 체크

---

db/users.db
public/stylesheets/style.css

[수정] 파란색 수정
